server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: cake-app
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
     url: jdbc:mysql://127.0.0.1/cake-fx?useUnicode=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    url: jdbc:p6spy:mysql://192.168.2.100/zblai-sync?useUnicode=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1443039998fu
    hikari:
      # 数据库连接池初始化 10
      minimum-idle: 100
      connection-timeout: 10000
#  redis:
#    host: 192.168.2.100
#    port: 6379
#    password: zblai617
mybatis-plus:
  type-aliases-package: com.zblai.core.model.mapper
  mapper-locations: classpath*:mapper/*.xml
